src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Category
{
    use Timestamps;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 60)]
    private ?string $title = null;

    #[ORM\Column(length: 60)]
    private ?string $slug = null;

    #[ORM\OneToMany(targetEntity: Category::class, mappedBy: 'parent')]
    private Collection $children;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'children')]
    #[ORM\JoinColumn(name: 'parent_id', referencedColumnName: 'id')]
    private Category|null $parent = null;

    #[ORM\OneToOne(targetEntity: Category::class)]
    #[ORM\JoinColumn(name: 'redirect_id', referencedColumnName: 'id')]
    private Category|null $redirect = null;

    /**
     * @var Collection<int, Link>
     */
    #[ORM\ManyToMany(targetEntity: Link::class, mappedBy: 'categories')]
    private Collection $links;

    #[ORM\Column(length: 60, nullable: true)]
    private ?string $news_slug = null;

    public function __construct() {
        $this->children = new ArrayCollection();
        $this->links = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getChildren(): Collection
    {
        return $this->children;
    }

    public function addChildren(Category $child): static
    {
        if (!$this->children->contains($child)) {
            $this->children->add($child);
            $child->setParent($this);
        }
        $this->children = $children;

        return $this;
    }

    public function removeChildren(Category $child): static
    {
        if ($this->children->removeElement($child)) {
            // set the owning side to null (unless already changed)
            if ($child->getParent() === $this) {
                $child->setParent(null);
            }
        }

        return $this;
    }

    public function getParent(): ?Category
    {
        return $this->parent;
    }

    public function setParent(?Category $parent): static
    {
        $this->parent = $parent;

        return $this;
    }

    public function getRedirect(): Category
    {
        return $this->redirect;
    }

    public function setRedirect(Category $redirect): static
    {
        $this->redirect = $redirect;

        return $this;
    }

    /**
     * @return Collection<int, Link>
     */
    public function getLinks(): Collection
    {
        return $this->links;
    }

    public function addLink(Link $link): static
    {
        if (!$this->links->contains($link)) {
            $this->links->add($link);
            $link->addCategory($this);
        }

        return $this;
    }

    public function removeLink(Link $link): static
    {
        if ($this->links->removeElement($link)) {
            $link->removeCategory($this);
        }

        return $this;
    }

    public function getNewsSlug(): ?string
    {
        return $this->news_slug;
    }

    public function setNewsSlug(?string $news_slug): static
    {
        $this->news_slug = $news_slug;

        return $this;
    }
}

templates/index/cool.html.twig
{% extends 'base.html.twig' %}

{% block title %}Neato!{% endblock %}

{% block body %}
<style>
    .wrapper { margin: 1em auto; max-width: 600px; width: 95%;}
    .center { text-align: center; }
</style>

<div class="wrapper">

</div>
{% endblock %}

templates/index/footer.html.twig
<div class="wrapper">

    <div class="center">
        {{ ""|date('Y') }} - Neato! - A project by <a href="{{ goth_link }}">GothPanda</a><br>
        {% if( app.user ) %}
            {{ app.user.username }}: <a href="{{ path('app_guide') }}">Guide Access</a> | <a href="{{ path('app_logout') }}">Logout</a>
        {% else %}
            <a href="{{ path('app_login') }}">Guide Login</a>
        {% endif %}
    </div>

</div>

templates/index/header.html.twig
<style>
    .wrapper { margin: 12px auto; max-width: 600px; width: 95%;}
    .center { text-align: center; }
</style>

<div class="wrapper">

    <div class="center">
        <img src="{{ asset('images/banner-image-map.gif') }}" alt="Neato!" usemap="#workmap" border="0">

        <map name="workmap">
            <area shape="rect" coords="200,0,400,60" alt="Neato!" href="{{ path('app_index') }}">
            <area shape="rect" coords="10,0,70,60" alt="New" href="{{ path('app_new') }}">
            <area shape="rect" coords="70,0,130,60" alt="Cool" href="{{ path('app_cool') }}">
            <area shape="rect" coords="130,0,190,60" alt="Random" href="{{ path('app_random') }}">
            <area shape="rect" coords="410,0,470,60" alt="News" href="{{ path('app_news') }}">
            <area shape="rect" coords="470,0,530,60" alt="Info" href="{{ path('app_info') }}">
            <area shape="rect" coords="530,0,590,60" alt="Add" href="{{ path('app_add') }}">
        </map>
    </div>
    
    <hr>

</div>

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Neato!{% endblock %}

{% block body %}

<div class="wrapper">

    <ul>
    {% for category in categories %}

        <li><a href="{{ path('app_category', {slug: category.slug}) }}"><b>{{ category.title }}</b></a> 
        {% if category.newsSlug is not null %}
            {%if category.newsSlug is empty %}
                <a href="{{ path('app_news') }}"><b>[Xtra!]</b></a>
            {% else %}
                <a href="{{ path('app_news_feed', {slug: category.newsSlug}) }}"><b>[Xtra!]</b></a>
            {% endif %}
        {% endif %}
        {% if category.children is not empty %}
        - -
            <i>
            {% for child in category.children %}
                <a href="{{ path('app_category', {slug: child.slug}) }}">{{ child.title }}</a>, 
            {% endfor %}
                <a href="{{ path('app_category', {slug: category.slug}) }}">...</a>
            </i>
        {% endif %}
        <p></p>
        </li>

    {% endfor %}
    </ul>
    <hr>

</div>
{% endblock %}

templates/index/info.html.twig
{% extends 'base.html.twig' %}

{% block title %}Neato!{% endblock %}

{% block body %}

<div class="wrapper">

    <p>Neato! is a web directory for <a href="https://cghmn.org">CGHMN</a>, 
    allowing people to share and discover services and resources on the network.
    </p>

    <p>Each category with an [Xtra!] link has a news feed associated with it.
    </p>

    <p>All news items are currently provided by 
    <a href="https://abcnews.go.com/Site/page/rss-feeds-3520115">ABC News RSS
    </a>. If you'd like to suggest a feed for inclusion, you can 
     <a href="mailto:{{ goth_email }}">shoot GothPanda an email</a>.</p>

    <p>All weather data is provided by <a href="https://open-meteo.com/">Open-Meteo.com</a></p>


    <p>Neato! was made by <a href="{{ goth_link }}">GothPanda</a>.</p>

    <hr>

</div>
{% endblock %}

templates/index/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Neato!{% endblock %}

{% block body %}

<div class="wrapper">
    <h2>New Links</h2>
    <hr>
</div>

{% if links is not empty %}
<div class="wrapper">

    <ul>
    {% for link in links %}

    {% if link.approved %}
        <li><a href="{{ link.url }}">{{ link.title }}</a>
        {% if link.createdAt|date() >= "-1 month"|date() %}<img src="{{ asset( 'images/new.gif' )}}">{% endif %}
         - {{ link.comment }}</li>
    {% endif %}

    {% endfor %}
    </ul>
    <hr>

</div>
{% endif %}

{% endblock %}